### ISSUE TITLE
lutris crashed with AttributeError in on_game_start(): 'NoneType' object has no attribute 'show'

### ISSUE THREAD

**Issue by ArkaneMoose** [lutris/agora#57]
Hi, everyone! I wanted to report a minor bug that occurs every time I launch a game from the Ubuntu launcher, which runs `/usr/bin/python3 /usr/games/lutris lutris:rungameid/2`. The game successfully runs, but I get Ubuntu&rsquo;s &ldquo;The application Lutris has closed unexpectedly&rdquo; dialog with the following traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 377, in on_game_start
    self.running_row.show()
AttributeError: 'NoneType' object has no attribute 'show'
```

Here's a snippet of the output when I run the same command from the terminal:
```
$ /usr/bin/python3 /usr/games/lutris lutris:rungameid/2
2020-12-15 13:47:23,757: Initializing lutris
2020-12-15 13:47:24,695: Runtime up-to-date. Initialization complete.
2020-12-15 13:47:24,711: Lutris 0.5.8.1
2020-12-15 13:47:24,712: Using NVIDIA drivers 455.45.01 for x86_64
2020-12-15 13:47:24,714: GPU: GeForce 940MX
2020-12-15 13:47:24,714: GPU: 10DE:134D 103C:8216 (nvidia drivers)
2020-12-15 13:47:24,715: GPU: 8086:5916 103C:8216 (i915 drivers)
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 377, in on_game_start
    self.running_row.show()
AttributeError: 'NoneType' object has no attribute 'show'
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Running gamemoderun /home/rishov/.local/share/lutris/runners/wine/lutris-6.0-rc1-x86_64/bin/wine /home/rishov/Games/Battle.net/drive_c/Program Files (x86)/Battle.net/Battle.net.exe
Initial process has started with pid 100718
Start monitoring process.
[...output from Battle.net process...]
```

The apport crash log is attached here: [_usr_games_lutris.1000.crash.txt](https://github.com/lutris/agora/files/5697957/_usr_games_lutris.1000.crash.txt)

Let me know if there&rsquo;s any more information you need. Thanks!

**Comment by strycore** [comment]
I think this happens when you quit lutris while the "running" section in the sidebar is selected.
You can workaround this by opening lutris, selecting another category then quitting lutris. This should fix your game shortcuts while we prepare a patch for the issue.
