### ISSUE TITLE
Can't launch Lutris on Void Linux

### ISSUE THREAD

**Issue by hrqmonteiro** [lutris/agora#93]
I can't launch Lutris in any way

I tried default installation, via `xbps-install lutris`, `tar.xz` and cloning the repo and trying to run.

I got this error:

```
Traceback (most recent call last):
  File "/bin/lutris", line 54, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 53, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3.9/site-packages/lutris/gui/lutriswindow.py", line 26, in <module>
    from lutris.gui.widgets.sidebar import LutrisSidebar
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/sidebar.py", line 6, in <module>
    from lutris import platforms, runners, services
  File "/usr/lib/python3.9/site-packages/lutris/platforms.py", line 19, in <module>
    _init_platforms()
  File "/usr/lib/python3.9/site-packages/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/lib/python3.9/site-packages/lutris/runners/wine.py", line 229, in __init__
    "default": dxvk.DXVKManager().version,
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dxvk.py", line 56, in version
    return self.versions[0]
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dxvk.py", line 45, in versions
    self._versions = self.load_dxvk_versions()
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dxvk.py", line 65, in load_dxvk_versions
    with open(versions_path, "r") as dxvk_version_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/hrq/.local/share/lutris/runtime/dxvk/dxvk_versions.json'
```

I tried everything, i have all the python requirements, i have dxvk installed, wine, and don't know what to do. I tried reddit help but the community didn't answered me.

**Comment by strycore** [comment]
This is not caused by Void, the current release has a bug that affects new installs.
You should be able to workaround with the following:

`mkdir -p ~/.local/share/lutris/runtime/dxvk/; touch ~/.local/share/lutris/runtime/dxvk/dxvk_versions.json`
